version: "3"

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - ./data:/var/lib/postgresql/data

  web:
    build: .
    restart: always
    ports:
      - 5000:5000
    depends_on:
      - db
